version: '2'

services:
    web:
        image: nginx:alpine
        expose:
            - "80"
        volumes:
            - ./files/web:/webfiles
            - ./site.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=DOMAIN
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=DOMAIN
            - LETSENCRYPT_EMAIL=EMAIL

    php:
        image: php:fpm-alpine
        volumes:
            - ./files/web:/webfiles

networks:
  default:
    external:
      name: nginx-proxy
